"""
Codegen for depth-resolved multivar fragments, driven by a single
depth-indices config (config/depths/*.yaml, key `depth_indices`: positions
in the truth file's depth axis).

Generates, for suffix S:
  config/vars/thetao_S.yaml, uo_S.yaml, vo_S.yaml    (full_output targets)
  config/vars/argo_virtual_thetao_S.yaml              (prior_input virtual-ARGO channels)

Entry naming: f"{var}_d{index:02d}" (index-based, value-agnostic - the exact
physical value lives in the file's depth axis and can be annotated in the
generated comments with --truth-path).

Validation: indices unique, non-negative, and (with --truth-path) in range;
duplicate-value aliasing is impossible by construction (isel).
"""
import argparse
from pathlib import Path

import yaml

HEAD_GROUPS = {'thetao': 'temperature_glorys', 'uo': 'currents_glorys_u', 'vo': 'currents_glorys_v'}


def load_indices(indices_yaml):
    with open(indices_yaml) as f:
        indices = yaml.safe_load(f)['depth_indices']
    if len(set(indices)) != len(indices):
        raise ValueError(f"duplicate depth indices in {indices_yaml}: {indices}")
    if any(int(i) < 0 for i in indices):
        raise ValueError(f"negative depth index in {indices_yaml}")
    return [int(i) for i in indices]


def resolve_depth_values(truth_path, indices):
    import xarray as xr
    depth = xr.open_dataset(truth_path)['depth'].values
    bad = [i for i in indices if i >= len(depth)]
    if bad:
        raise ValueError(f"indices {bad} out of range: truth file has {len(depth)} depth levels")
    return [float(depth[i]) for i in indices]


def _fragment(entries, values=None, indices=None):
    header = "# @package multivar\n# GENERATED by contrib/data_loading/depth_fragments.py - edit config/depths/*, not this file.\n"
    if values is not None:
        header += "# depth index -> value (m): " + ", ".join(
            f"{i}:{v:.2f}" for i, v in zip(indices, values)) + "\n"
    return header + yaml.safe_dump(entries, sort_keys=False)


def generate(indices_yaml, suffix, out_dir='config/vars', truth_path=None,
             glorys_path_key='${paths.glorys_multidepth}',
             argo_dir_key='${paths.data_root}/argo_virtual/gridded'):
    indices = load_indices(indices_yaml)
    values = resolve_depth_values(truth_path, indices) if truth_path else None
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    for var in ('thetao', 'uo', 'vo'):
        entries = {
            f"{var}_d{i:02d}": dict(
                var_path=glorys_path_key, var_name=var,
                input_arch='no_input', output_arch='full_output',
                broadcast_time=False, head_group=HEAD_GROUPS[var], depth_index=i,
            )
            for i in indices
        }
        path = out_dir / f"{var}_{suffix}.yaml"
        path.write_text(_fragment(entries, values, indices))
        written.append(path)

    argo_entries = {
        f"argo_thetao_d{i:02d}": dict(
            var_path=f"{argo_dir_key}/thetao_vargo_d{i:02d}.nc", var_name='thetao_vargo',
            input_arch='prior_input', output_arch='no_output', broadcast_time=False,
        )
        for i in indices
    }
    path = out_dir / f"argo_virtual_thetao_{suffix}.yaml"
    path.write_text(_fragment(argo_entries, values, indices))
    written.append(path)

    for p in written:
        print(f"wrote {p} ({len(indices)} levels)")
    return written


def _cli():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--indices-yaml', required=True)
    p.add_argument('--suffix', required=True, help="e.g. gs21 -> config/vars/thetao_gs21.yaml ...")
    p.add_argument('--truth-path', default=None, help="optional: validates range and annotates values")
    p.add_argument('--out-dir', default='config/vars')
    args = p.parse_args()
    generate(args.indices_yaml, args.suffix, out_dir=args.out_dir, truth_path=args.truth_path)


if __name__ == '__main__':
    _cli()
