# @package multivar
uo_0.49m:
  var_path: ${paths.glorys_multidepth}
  var_name: uo
  input_arch: no_input
  output_arch: full_output
  broadcast_time: false
  head_group: currents_glorys
  depth_level: 0.49
uo_15m:
  var_path: ${paths.glorys_multidepth}
  var_name: uo
  input_arch: no_input
  output_arch: full_output
  broadcast_time: false
  head_group: currents_glorys
  depth_level: 15
uo_50m:
  var_path: ${paths.glorys_multidepth}
  var_name: uo
  input_arch: no_input
  output_arch: full_output
  broadcast_time: false
  head_group: currents_glorys
  depth_level: 50
uo_100m:
  var_path: ${paths.glorys_multidepth}
  var_name: uo
  input_arch: no_input
  output_arch: full_output
  broadcast_time: false
  head_group: currents_glorys
  depth_level: 100
uo_200m:
  var_path: ${paths.glorys_multidepth}
  var_name: uo
  input_arch: no_input
  output_arch: full_output
  broadcast_time: false
  head_group: currents_glorys
  depth_level: 200
