# @package multivar
vo_0.49m:
  var_path: /Odyssey/private/t22picar/data/glorys_multidepth/glorys_multidepth_2010-2020.nc
  var_name: vo
  input_arch: no_input
  output_arch: full_output
  broadcast_time: false
  head_group: currents_glorys
  depth_level: 0.49
vo_15m:
  var_path: /Odyssey/private/t22picar/data/glorys_multidepth/glorys_multidepth_2010-2020.nc
  var_name: vo
  input_arch: no_input
  output_arch: full_output
  broadcast_time: false
  head_group: currents_glorys
  depth_level: 15
vo_50m:
  var_path: /Odyssey/private/t22picar/data/glorys_multidepth/glorys_multidepth_2010-2020.nc
  var_name: vo
  input_arch: no_input
  output_arch: full_output
  broadcast_time: false
  head_group: currents_glorys
  depth_level: 50
vo_100m:
  var_path: /Odyssey/private/t22picar/data/glorys_multidepth/glorys_multidepth_2010-2020.nc
  var_name: vo
  input_arch: no_input
  output_arch: full_output
  broadcast_time: false
  head_group: currents_glorys
  depth_level: 100
vo_200m:
  var_path: /Odyssey/private/t22picar/data/glorys_multidepth/glorys_multidepth_2010-2020.nc
  var_name: vo
  input_arch: no_input
  output_arch: full_output
  broadcast_time: false
  head_group: currents_glorys
  depth_level: 200
