"""
Orchestrates the real CNES/JPL swot_simulator (settings generated by
contrib.synthetic_obs.swot_official_settings) and rasterizes its output onto
the NOSC target grid, in two forms:

- a daily coverage-mask pickle, byte-compatible with the existing mask_path
  contract (process_data/mask/glorys_masking.ipynb / contrib/data_loading/
  data.py's mask_input) - the same contract contrib.synthetic_obs.build_masks
  (the closed-form propagator) already targets.
- optionally, the actual noisy simulated SSH values (ssh_karin, i.e. the
  real KaRIn instrument-noise model applied to the Glorys "truth"), which is
  a genuinely different, higher-fidelity artifact than a plain coverage mask
  - real simulated pseudo-observations, not just a sampling pattern.

Only the SWOT platform (karin swath + its onboard nadir altimeter) is
covered here; other nadir missions are outside swot_simulator's scope (see
swot_official_settings.py's docstring).
"""
import os
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

from contrib.synthetic_obs.build_masks import serialize_masks
from contrib.synthetic_obs.sampling import nearest_grid_indices


def run_swot_simulator(settings_path, first_date, last_date, n_workers=1, extra_pythonpath=None):
    """Runs the swot_simulator CLI as a subprocess (the tool's own documented
    entrypoint - it manages its own Dask cluster internally)."""
    repo_root = str(Path(__file__).resolve().parents[2])  # code/multivar_drifter_
    env = os.environ.copy()
    pythonpath_parts = [repo_root]
    if extra_pythonpath:
        pythonpath_parts.append(str(extra_pythonpath))
    if env.get('PYTHONPATH'):
        pythonpath_parts.append(env['PYTHONPATH'])
    env['PYTHONPATH'] = os.pathsep.join(pythonpath_parts)

    subprocess.run(
        ['swot_simulator', str(settings_path), '--first-date', str(first_date),
         '--last-date', str(last_date), '--n-workers', str(n_workers)],
        check=True, env=env,
    )


def _karin_points(path):
    ds = xr.open_dataset(path)
    lon = ds['longitude'].values
    lat = ds['latitude'].values
    time = np.broadcast_to(ds['time'].values[:, None], lon.shape)
    ssh = ds['ssh_karin'].values if 'ssh_karin' in ds else None
    return lon.ravel(), lat.ravel(), time.ravel(), (ssh.ravel() if ssh is not None else None)


def _nadir_points(path):
    ds = xr.open_dataset(path, group='data_01')
    lon, lat, time = ds['longitude'].values, ds['latitude'].values, ds['time'].values
    ssh = ds['ssh'].values if 'ssh' in ds else None
    return lon, lat, time, ssh


def _iter_pass_points(working_directory, products):
    for product in products:
        product_dir = Path(working_directory, product)
        if not product_dir.exists():
            continue
        reader = _karin_points if product == 'karin' else _nadir_points
        for path in sorted(product_dir.rglob('*.nc')):
            yield reader(path)


def rasterize_swot_official(
    working_directory, lat_grid, lon_grid, start_date, end_date,
    products=('karin', 'nadir'), with_values=False,
):
    """
    Bins swot_simulator's raw pass output onto (lat_grid, lon_grid), one
    entry per day in [start_date, end_date).

    Returns a list of daily float32 (n_lat, n_lon) arrays: 1.0 (or the
    noisy ssh value if with_values=True) where observed that day, NaN
    elsewhere - the same contract as contrib.synthetic_obs.sampling.
    build_daily_masks / process_data/mask/glorys_masking.ipynb.
    """
    lat_grid, lon_grid = np.asarray(lat_grid), np.asarray(lon_grid)
    dates = pd.date_range(start_date, end_date, freq='D')
    date_index = {pd.Timestamp(d).normalize(): i for i, d in enumerate(dates)}

    grids = [np.full((len(lat_grid), len(lon_grid)), np.nan, dtype=np.float32) for _ in dates]

    for lon, lat, time, ssh in _iter_pass_points(working_directory, products):
        days = pd.DatetimeIndex(time).normalize()
        for day, day_index in date_index.items():
            in_day = days == day
            if not np.any(in_day):
                continue
            row, col = nearest_grid_indices(lat[in_day], lon[in_day], lat_grid, lon_grid)
            if with_values and ssh is not None:
                grids[day_index][row, col] = ssh[in_day][:len(row)]
            else:
                grids[day_index][row, col] = 1.0

    return grids


def build_and_serialize_swot_official_masks(
    output_path, working_directory, lat_grid, lon_grid, start_date, end_date,
    products=('karin', 'nadir'), with_values=False,
):
    masks = rasterize_swot_official(
        working_directory, lat_grid, lon_grid, start_date, end_date,
        products=products, with_values=with_values,
    )
    serialize_masks(output_path, masks)
    return masks
