"""
Generates a settings.py file for the real CNES/JPL `swot_simulator` package
(https://github.com/CNES/swot_simulator, pip package `swot-simulator`),
using contrib.synthetic_obs.glorys_ssh_plugin.Glorys12 as the ssh_plugin so
it propagates SWOT's actual published ephemeris (real orbit, not the
closed-form approximation in contrib/synthetic_obs/orbits.py) over a NOSC
Glorys source file, with the real KaRIn instrument noise model.

This complements, rather than replaces, orbits.py/missions.py: swot_simulator
only covers the SWOT platform (its KaRIn wide-swath instrument and onboard
nadir altimeter, sharing one orbit) - it ships no ephemeris for the other
historical nadir missions (Jason-3, Sentinel-3, SARAL, HY-2B...) that
orbits.py's closed-form propagator was built to approximate. For those,
this codebase's existing practice (real historical along-track coverage,
see process_data/mask/glorys_masking.ipynb) is arguably more faithful than
simulating orbits for satellites that already really flew.
"""
import os
from pathlib import Path

import swot_simulator.settings as _settings

DATA_DIR = os.path.join(os.path.dirname(_settings.__file__), 'data')

EPHEMERIS_FILES = {
    'science': 'ephemeris_science_sept2015_ell.txt',
    'calval': 'ephemeris_calval_june2015_ell.txt',
}

DEFAULT_NOISE = ['karin', 'altimeter', 'orbital', 'timing']


def write_settings_file(
    output_path,
    glorys_path,
    working_directory,
    glorys_var='zos',
    area=None,
    ephemeris='science',
    noise=DEFAULT_NOISE,
    nadir=True,
    swath=True,
    product_type='expert',
    nseed=0,
):
    """
    area: (lon_min, lat_min, lon_max, lat_max) or None for global.
    Returns the settings file path (== output_path).
    """
    ephemeris_path = os.path.join(DATA_DIR, EPHEMERIS_FILES[ephemeris])
    content = f'''# Auto-generated by contrib.synthetic_obs.swot_official_settings - do not edit by hand.
import os
import swot_simulator.settings as settings
import contrib.synthetic_obs.glorys_ssh_plugin as glorys_ssh_plugin

DATA = {DATA_DIR!r}

ephemeris = {ephemeris_path!r}
error_spectrum = os.path.join(DATA, 'error_spectrum.nc')
karin_noise = os.path.join(DATA, 'karin_noise_v2.nc')

area = {tuple(area) if area is not None else None!r}
working_directory = {str(working_directory)!r}
nadir = {bool(nadir)!r}
swath = {bool(swath)!r}
product_type = {product_type!r}
noise = {list(noise)!r}
nseed = {int(nseed)!r}

ssh_plugin = glorys_ssh_plugin.Glorys12({str(glorys_path)!r}, var_name={glorys_var!r})
'''
    Path(output_path).write_text(content)
    return output_path
